//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoencomEntities : DbContext
    {
        public VoencomEntities()
            : base("name=VoencomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prizivnik> Prizivnik { get; set; }
        public virtual DbSet<Spisokprizivnokov> Spisokprizivnokov { get; set; }
        public virtual DbSet<zdorovie> zdorovie { get; set; }
    }
}
