//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prizivnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prizivnik()
        {
            this.Spisokprizivnokov = new HashSet<Spisokprizivnokov>();
        }
    
        public int ID_prizivnik { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string Middlename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spisokprizivnokov> Spisokprizivnokov { get; set; }
    }
}
