//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spisokprizivnokov
    {
        public int ID_Spisokprizivnokov { get; set; }
        public Nullable<int> Prizivnik_ID { get; set; }
        public Nullable<int> zrenie_ID { get; set; }
        public Nullable<int> ploskostopie_ID { get; set; }
        public Nullable<int> zelanie_ID { get; set; }
        public Nullable<int> perelom_ID { get; set; }
        public Nullable<int> zdorovie_ID { get; set; }
        public int Vozrast { get; set; }
        public int Rost { get; set; }
        public string AO { get; set; }
        public string Ychitsa { get; set; }
    
        public virtual Prizivnik Prizivnik { get; set; }
        public virtual zdorovie zdorovie { get; set; }
    }
}
